baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Web site HUGO'
theme= 'tale'

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "HOME"
	url = "/HOME/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0